---
ID: "0088736c-20ec-498b-a583-793bc9a2e8b2"
Parent: "64039a20-99d2-4ce8-b75c-092cd9e06c0a"
Template: "64039a20-99d2-4ce8-b75c-092cd9e06c0a"
Path: "/sitecore/templates/Project/alain-site-core-nextjs/Pages/App Route/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{DC978489-8963-4282-BE19-1E5D93CC1844}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4F760EC1-A659-4214-BF87-D4F38FA41975}">
        <r
          id="{CDCCAD46-9B35-4EDC-A4C5-B8DF3C65A482}"
          ph="jss-header"
          uid="{05418581-E6A2-46AC-BDBF-C222703A6F0D}" />
        <r
          id="{A02EFEFF-E1C9-4449-B5F7-E7AC79FD296B}"
          ph="jss-footer"
          uid="{ACA1BD09-B59B-449F-A32E-3889D60D7CB0}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250530T094209Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e707623c-cebf-4921-9f26-69c1e5d5a2fb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250912T144127Z
