---
ID: "1f716cef-d4c8-40be-aa3d-3a141b5d9598"
Parent: "bffd32e0-130d-47c0-a718-c6ed69aaf909"
Template: "bffd32e0-130d-47c0-a718-c6ed69aaf909"
Path: /sitecore/templates/Foundation/Common/_Base/_AlaimItem/__Standard Values
SharedFields:
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250914T183554Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zaheer
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zaheer
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb83f565-5b00-476d-ad76-6af65e4c9b80"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zaheer
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250914T231146Z
