version: "3.9"
services:
  frontend-sitecore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-sitecore
    ports:
      - "3004:3000"
    environment:
      # NODE_ENV: production
      # PORT: 3000
      PUBLIC_URL: https://alain-museum.arimac.digital
    restart: unless-stopped